version: '2'

services:
 v2ray:
    image: alliswell2day/v2:go
    restart: always
    network_mode: "host"
    environment:
      sspanel_url: "https://xxxx"
      key: "Alliswell2day1477"
      speedtest: 6
      node_id: 10
      api_port: 4444
    logging:
      options:
        max-size: "10m"
        max-file: "3"
